server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      httpclient:
        ssl:
          useInsecureTrustManager: true
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/auth/**
          filters:
            - PreserveHostHeader

        - id: usuario-service
          uri: ${AUTH_SERVICE_URL:http://localhost:8081}
          predicates:
            - Path=/api/usuarios/**
          filters:
            - PreserveHostHeader

        - id: cliente-service
          uri: ${CLIENT_SERVICE_URL:http://localhost:8082}
          predicates:
            - Path=/api/clientes/**
          filters:
            - PreserveHostHeader

        - id: pago-service
          uri: ${PAGO_SERVICE_URL:http://localhost:8083}
          predicates:
            - Path=/api/pagos/**
          filters:
            - PreserveHostHeader

        - id: notificacion-service
          uri: ${NOTIFICACION_SERVICE_URL:http://localhost:8084}
          predicates:
            - Path=/api/notificaciones/**
          filters:
            - PreserveHostHeader

jwt:
  secret: ${JWT_SECRET}