server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: usuario-service
          uri: lb://auth-service
          predicates:
            - Path=/api/usuarios/**
        - id: cliente-service
          uri: lb://cliente-service
          predicates:
            - Path=/api/clientes/**
        - id: pago-service
          uri: lb://pago-service
          predicates:
            - Path=/api/pagos/**
        - id: notificacion-service
          uri: lb://notificacion-service
          predicates:
            - Path=/api/notificaciones/**

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: https://ebenecer-eureka.onrender.com/eureka/
  instance:
    hostname: ebenecer-gateway.onrender.com
    prefer-ip-address: falsegit