server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: ${DB_AUTH_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    jpa:
      properties:
        hibernate:
          default_schema: auth_schema

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

admin:
  default:
    password: ${ADMIN_DEFAULT_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true