server:
  port: ${PORT:8083}

spring:
  application:
    name: pago-service

  datasource:
    url: ${DB_PAGO_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: pago_schema
    hibernate:
      ddl-auto: update

  cloud:
    openfeign:
      client:
        config:
          cliente-service:
            url: https://ebenecer-clientes.onrender.com # Usa la URL real
            connectTimeout: 10000 # 10 segundos
            readTimeout: 30000    # 30 segundos (vital para el cold start de Render)
          default:
            connectTimeout: 5000
            readTimeout: 5000

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
    ssl:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ebenecer-pagos.onrender.com
    prefer-ip-address: false
    non-secure-port: 80