server:
  port: 8083

spring:
  application:
    name: pago-service

  datasource:
    url: ${DB_PAGO_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        default_schema: pago_schema

  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    ssl:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: https://ebenecer-eureka.onrender.com/eureka/
  instance:
    prefer-ip-address: false
