server:
  port: ${PORT:8084}

spring:
  application:
    name: notificacion-service

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
    ssl:
      enabled: true

empresa:
  nombre: Cable Ebenecer Trujillo
  email: onboarding@resend.dev
  datos-pago: "Yape/Plin: 987 298 465 | Oficina: Trujillo"

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    hostname: ebenecer-notificaciones.onrender.com
    prefer-ip-address: false
    non-secure-port: 80